-- Surgical cleanup assertions.
-- Run with: nvim --headless -c 'lua require("plenary.busted").run("tests/test_cleanup.lua")' -c 'qa!'
describe('surgical cleanup', function()
  local H = require('tests.helpers')
  describe('M1 actions-preview', function()
    it('uses the snacks backend, not telescope', function()
      local code = H.code()
      local spec = code:match "'aznhe21/actions%-preview%.nvim'.-\n  %},"
      assert.is_not_nil(spec, 'actions-preview spec should exist')
      assert.is_truthy(spec:match "backend%s*=%s*{%s*'snacks'", 'backend must be snacks')
      assert.is_nil(spec:match 'telescope', 'no telescope string in the actions-preview block')
    end)
  end)
  describe('M2 todo picker', function()
    it('<leader>st uses snacks todo_comments, TodoTelescope is gone', function()
      local code = H.code()
      assert.is_nil(code:match 'TodoTelescope', 'TodoTelescope must be gone')
      assert.is_truthy(code:match "<leader>st.-require%('snacks'%).picker%.todo_comments%s*%(", '<leader>st must call snacks picker todo_comments')
    end)
  end)
  describe('R4/M4 lsp progress', function()
    it('fidget is gone; statusline shows vim.lsp.status()', function()
      local code = H.code()
      assert.is_nil(code:match 'fidget%.nvim', 'fidget spec must be gone')
      assert.is_truthy(code:match 'vim%.lsp%.status%s*%(%s*%)', 'statusline must read vim.lsp.status()')
      assert.is_truthy(code:match "prog%s*~=%s*''", 'statusline must branch on live progress')
      assert.is_truthy(code:match "gsub%('%%%%', '%%%%%%%%'%)", 'progress text must be percent-escaped')
    end)
  end)
  describe('R1 neo-tree', function()
    it('neo-tree spec and close calls are gone', function()
      local code = H.code()
      assert.is_nil(code:match 'neo%-tree%.nvim', 'no neo-tree spec must remain')
      assert.is_nil(code:match 'Neotree%s+close', 'no :Neotree close calls must remain')
      assert.is_nil(code:match "filetype%s*==%s*'neo%-tree'", 'no neo-tree filetype guard must remain')
    end)
  end)
end)
