-- Surgical cleanup assertions.
-- Run with: nvim --headless -c 'lua require("plenary.busted").run("tests/test_cleanup.lua")' -c 'qa!'
describe('surgical cleanup', function()
  local H = require('tests.helpers')
  describe('M1 actions-preview', function()
    it('uses the snacks backend, not telescope', function()
      local code = H.code()
      local spec = code:match "'aznhe21/actions%-preview%.nvim'.-\n  %},"
      assert.is_not_nil(spec, 'actions-preview spec should exist')
      assert.is_truthy(spec:match "backend%s*=%s*{%s*'snacks'", 'backend must be snacks')
      assert.is_nil(spec:match 'telescope', 'no telescope string in the actions-preview block')
    end)
  end)
  describe('M2 todo picker', function()
    it('<leader>st uses snacks todo_comments, TodoTelescope is gone', function()
      local code = H.code()
      assert.is_nil(code:match 'TodoTelescope', 'TodoTelescope must be gone')
      assert.is_truthy(code:match "<leader>st.-require%('snacks'%).picker%.todo_comments%s*%(", '<leader>st must call snacks picker todo_comments')
    end)
  end)
  describe('R4/M4 lsp progress', function()
    it('fidget is gone; statusline shows vim.lsp.status()', function()
      local code = H.code()
      assert.is_nil(code:match 'fidget%.nvim', 'fidget spec must be gone')
      assert.is_truthy(code:match 'vim%.lsp%.status%s*%(%s*%)', 'statusline must read vim.lsp.status()')
      assert.is_truthy(code:match "prog%s*~=%s*''", 'statusline must branch on live progress')
      assert.is_truthy(code:match "gsub%('%%%%', '%%%%%%%%'%)", 'progress text must be percent-escaped')
    end)
  end)
  describe('R1 neo-tree', function()
    it('neo-tree spec and close calls are gone', function()
      local code = H.code()
      assert.is_nil(code:match 'neo%-tree%.nvim', 'no neo-tree spec must remain')
      assert.is_nil(code:match 'Neotree%s+close', 'no :Neotree close calls must remain')
      assert.is_nil(code:match "filetype%s*==%s*'neo%-tree'", 'no neo-tree filetype guard must remain')
    end)
  end)
  describe('R2 telescope', function()
    it('telescope, fzf-native and ui-select specs are gone', function()
      local code = H.code()
      assert.is_nil(code:match 'nvim%-telescope/telescope%.nvim', 'telescope spec must be gone')
      assert.is_nil(code:match 'fzf%-native%.nvim', 'fzf-native spec must be gone')
      assert.is_nil(code:match 'telescope%-ui%-select', 'ui-select spec must be gone')
    end)
  end)
  describe('M5 session picker', function()
    it('dashboard session picker has no telescope branch', function()
      local code = H.code()
      assert.is_nil(code:match 'telescope%.pickers', 'dashboard must not require telescope pickers')
      assert.is_truthy(code:match 'vim%.ui%.select%s*%(', 'vim.ui.select fallback must remain')
    end)
  end)
  describe('R3 bookmarks', function()
    it('vim-bookmarks specs and keys are gone', function()
      local code = H.code()
      assert.is_nil(code:match 'vim%-bookmarks', 'no vim-bookmarks refs must remain')
      assert.is_nil(code:match 'BookmarkToggle', 'no bookmark commands must remain')
    end)
  end)
  describe('F1/F2 modern APIs', function()
    it('lazyredraw is on; win32 check uses vim.uv', function()
      local code = H.code()
      assert.is_truthy(code:match 'lazyredraw%s*=%s*true', 'lazyredraw must be re-enabled (noice is gone)')
      assert.is_nil(code:match "has%s*'win32'", 'legacy has-win32 check must be gone')
      assert.is_truthy(code:match 'os_uname%s*%(%s*%)%.sysname', 'platform check must use vim.uv.os_uname')
    end)
  end)
  describe('F3 health check', function()
    it('no fzf-native rows; make row names luasnip', function()
      local c = H.read(vim.fn.stdpath 'config' .. '/lua/config/health.lua')
      assert.is_nil(c:match 'fzf', 'no fzf-native rows must remain')
      assert.is_nil(c:match 'cmake', 'cmake row must be gone with fzf-native')
      assert.is_truthy(c:match '[Ll]uaSnip', 'make row must name the LuaSnip build')
    end)
  end)
end)
